// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tqqeutfiufeargocwwrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRxcWV1dGZpdWZlYXJnb2N3d3J3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjIzMzUsImV4cCI6MjA2NDc5ODMzNX0.plBwLqEXXWTjb2-WM2QuxflEKjZOspg4EvvQ1KavKAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);